version: '2'
networks:
  public-network:
    external:
      name: proxy

volumes:
  gems:
    driver: local
      
services:
  web:
    image: neilsmind/ruby-app:2.3
    command: bundle exec jekyll serve
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    working_dir: /app
    networks:
      - public-network
    expose:
      - 4000
    environment:
      VIRTUAL_HOST: blog.dev
